spring:
  mvc:
    # 处理 favicon
    favicon:
      enable: false
  # 错误页处理
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  # 数据库配置
  datasource:
    url: jdbc:mysql://52.253.118.106:3306/healwrap?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: HealWrap
    password: HealWrap
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      connect-timeout: 60000
      validation-query: SELECT 1

  # 发送邮件配置相关
  mail:
    host: smtp.qq.com
    port: 465
    username: 179763003@qq.com
    password: icokywqucbkkcbed
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true

# 项目目录
project:
  folder: /www/wwwroot/HealWrap-Backend/files/
  defaultAvatar: default_avatar.jpg
  defaultCover: default/default_cover.jpeg

# 内部接口相关
inner:
  api:
    appKey: healwrap
    appSecret: healwrap_key
    # web 端接口地址
    url: http://52.253.118.106:7070/api/inner/refreshSysSetting

# 是否是开发环境
development: false
