# 项目相关配置
healwrap:
  # 名称
  name: healwrap
  # 版本
  version: 1.0.0

server:
  servlet:
    # 配置 API 路径
    context-path: /api
    # session 过期时间 30M 半个小时
    session:
      timeout: PT30M
  # 配置端口
  port: 7071

spring:
  profiles:
    active: @profileActive@

# 日志级别配置
log:
  root:
    level: info


# 配置管理员账号密码邮箱
admin:
  email: pepedd@qq.com
  password: 12345678
