export const TOGGLE_MOBILE_TYPE = 'is_mobile'
export const TOGGLE_EDITOR_TYPE = 'is_editor'
export const TOGGLE_THEME = 'theme'
export const TOGGLE_CONTENT_WIDTH = 'content_width'
export const TOGGLE_HEADER_HEIGHT = 'header_height'
export const ENTER_APP = 'enter_app'
export const UPDATE_MESSAGE_COUNT = 'message_count'
