# 项目相关配置
healwrap:
  # 名称
  name: healwrap
  # 版本
  version: 1.0.0

server:
  servlet:
    # 配置 API 路径
    context-path: /api
    # session 过期时间 60M 一个小时
    session:
      timeout: PT60M
  # 配置端口
  port: 7070

spring:
  profiles:
    active: @profileActive@

# 配置管理员账号密码邮箱
admin:
  account: admin
  password: admin123
  emails: test@qq.com
